In [251]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
path = r'C:\Users\Tesla Laptops\Desktop\Job planning\Portfolio Project\TNO - Crimes in London\data\raw\M1045_MonthlyCrimeDashboard_TNOCrimeData.csv'

In [13]:
df = pd.read_csv(path)

In [15]:
df.head()

,Month_Year,Area Type,Borough_SNT,Area name,Area code,Offence Group,Offence Subgroup,Measure,Financial Year,FY_FYIndex,Count,Refresh Date
0,01/06/2021,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,BURGLARY,BURGLARY - BUSINESS AND COMMUNITY,Positive Outcomes,fy21-22,21-22_01,1,05/06/2025
1,01/06/2021,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,BURGLARY,BURGLARY - RESIDENTIAL,Positive Outcomes,fy21-22,21-22_01,2,05/06/2025
2,01/06/2021,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,Positive Outcomes,fy21-22,21-22_01,13,05/06/2025
3,01/06/2021,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,DRUG OFFENCES,TRAFFICKING OF DRUGS,Positive Outcomes,fy21-22,21-22_01,5,05/06/2025
4,01/06/2021,Borough,Barking and Dagenham,Barking and Dagenham,E09000002,PUBLIC ORDER OFFENCES,OTHER OFFENCES PUBLIC ORDER,Offences,fy21-22,21-22_01,14,05/06/2025

In [17]:
df.shape

(791224, 12)

In [19]:
df.columns

Index(['Month_Year', 'Area Type', 'Borough_SNT', 'Area name', 'Area code',
       'Offence Group', 'Offence Subgroup', 'Measure', 'Financial Year',
       'FY_FYIndex', 'Count', 'Refresh Date'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791224 entries, 0 to 791223
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Month_Year        791224 non-null  object
 1   Area Type         791224 non-null  object
 2   Borough_SNT       791224 non-null  object
 3   Area name         790599 non-null  object
 4   Area code         788005 non-null  object
 5   Offence Group     791224 non-null  object
 6   Offence Subgroup  791224 non-null  object
 7   Measure           791224 non-null  object
 8   Financial Year    791224 non-null  object
 9   FY_FYIndex        791224 non-null  object
 10  Count             791224 non-null  int64
 11  Refresh Date      791224 non-null  object
dtypes: int64(1), object(11)
memory usage: 72.4+ MB

In [23]:
df.isnull().sum()

Month_Year             0
Area Type              0
Borough_SNT            0
Area name            625
Area code           3219
Offence Group          0
Offence Subgroup       0
Measure                0
Financial Year         0
FY_FYIndex             0
Count                  0
Refresh Date           0
dtype: int64

In [33]:
df['Month_Year'] = pd.to_datetime(df['Month_Year'], dayfirst=True)
df['Refresh Date'] = pd.to_datetime(df['Refresh Date'], dayfirst=True)

In [39]:
df['Area Type'].unique()

array(['Borough', 'Safer Neighbourhood Teams'], dtype=object)

In [41]:
df['Measure'].unique()

array(['Positive Outcomes', 'Offences'], dtype=object)

In [43]:
df[df['Borough_SNT'] != df['Area name']]

,Month_Year,Area Type,Borough_SNT,Area name,Area code,Offence Group,Offence Subgroup,Measure,Financial Year,FY_FYIndex,Count,Refresh Date
871,2021-06-01,Borough,N/K,Other / NK,NaN,ARSON AND CRIMINAL DAMAGE,ARSON,Offences,fy21-22,21-22_01,4,2025-06-05
872,2021-06-01,Borough,N/K,Other / NK,NaN,PUBLIC ORDER OFFENCES,PUBLIC FEAR ALARM OR DISTRESS,Positive Outcomes,fy21-22,21-22_01,6,2025-06-05
882,2021-06-01,Borough,N/K,Other / NK,NaN,SEXUAL OFFENCES,RAPE,Offences,fy21-22,21-22_01,111,2025-06-05
883,2021-06-01,Borough,N/K,Other / NK,NaN,SEXUAL OFFENCES,RAPE,Positive Outcomes,fy21-22,21-22_01,1,2025-06-05
886,2021-06-01,Borough,N/K,Other / NK,NaN,THEFT,BICYCLE THEFT,Offences,fy21-22,21-22_01,44,2025-06-05
...,...,...,...,...,...,...,...,...,...,...,...,...
791219,2025-05-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,PUBLIC ORDER OFFENCES,OTHER OFFENCES PUBLIC ORDER,Offences,fy25-26,25-26_01,1,2025-06-05
791220,2025-05-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,PUBLIC ORDER OFFENCES,PUBLIC FEAR ALARM OR DISTRESS,Offences,fy25-26,25-26_01,3,2025-06-05
791221,2025-05-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,VIOLENCE AGAINST THE PERSON,VIOLENCE WITH INJURY,Offences,fy25-26,25-26_01,5,2025-06-05
791222,2025-05-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,VIOLENCE AGAINST THE PERSON,VIOLENCE WITHOUT INJURY,Offences,fy25-26,25-26_01,34,2025-06-05
791223,2025-05-01,Safer Neighbourhood Teams,Westminster Westbourne,Westbourne,E05013809,VIOLENCE AGAINST THE PERSON,VIOLENCE WITHOUT INJURY,Positive Outcomes,fy25-26,25-26_01,4,2025-06-05

In [49]:
# Unique mismatch combination
df[df['Borough_SNT'] != df['Area name']][['Borough_SNT', 'Area name']].drop_duplicates()

,Borough_SNT,Area name
871,N/K,Other / NK
1365,Barking and Dagenham Abbey,Abbey
1375,Barking and Dagenham Alibon,Alibon
1380,Barking and Dagenham Barking Riverside,Barking Riverside
1383,Barking and Dagenham Beam,Beam
...,...,...
619938,Hounslow Hounslow Central,Hounslow Central (NOT ACTIVE)
626998,Lambeth Clapham Town,Clapham Town (NOT ACTIVE)
671592,Camden St Pancras & Somers Town,St Pancras & Somers Town (NOT ACTIVE)
771404,Westminster Vincent Square,Vincent Square (NOT ACTIVE)
783416,Ealing Acton Central,Acton Central (NOT ACTIVE)

In [51]:
df['Borough_SNT'].unique()

array(['Barking and Dagenham', 'Barnet', 'Bexley', 'Brent', 'Bromley',
       'Camden', 'Croydon', 'Ealing', 'Enfield', 'Greenwich', 'Hackney',
       'Hammersmith and Fulham', 'Haringey', 'Harrow', 'Havering',
       'Hillingdon', 'Hounslow', 'Islington', 'Kensington and Chelsea',
       'Kingston upon Thames', 'Lambeth', 'Lewisham', 'Merton', 'N/K',
       'Newham', 'Redbridge', 'Richmond upon Thames', 'Southwark',
       'Sutton', 'Tower Hamlets', 'Other / NK', 'Waltham Forest',
       'Wandsworth', 'Westminster', 'Barking and Dagenham Abbey',
       'Barking and Dagenham Alibon',
       'Barking and Dagenham Barking Riverside',
       'Barking and Dagenham Beam', 'Barking and Dagenham Becontree',
       'Barking and Dagenham Chadwell Heath',
       'Barking and Dagenham Eastbrook & Rush Green',
       'Barking and Dagenham Eastbury', 'Barking and Dagenham Gascoigne',
       'Barking and Dagenham Goresbrook', 'Barking and Dagenham Heath',
       'Barking and Dagenham Longbridge',
       'Barking and Dagenham Mayesbrook',
       'Barking and Dagenham Northbury', 'Barking and Dagenham Parsloes',
       'Barking and Dagenham Thames View', 'Barking and Dagenham Valence',
       'Barking and Dagenham Village', 'Barking and Dagenham Whalebone',
       'Barnet Barnet Vale', 'Barnet Brunswick Park', 'Barnet Burnt Oak',
       'Barnet Childs Hill', 'Barnet Colindale North',
       'Barnet Colindale South', 'Barnet Cricklewood',
       'Barnet East Barnet', 'Barnet East Finchley', 'Barnet Edgware',
       'Barnet Edgwarebury', 'Barnet Finchley Church End',
       'Barnet Friern Barnet', 'Barnet Garden Suburb',
       'Barnet Golders Green', 'Barnet Hendon', 'Barnet High Barnet',
       'Barnet Mill Hill', 'Barnet Totteridge & Woodside',
       'Barnet Underhill', 'Barnet West Finchley', 'Barnet West Hendon',
       'Barnet Whetstone', 'Barnet Woodhouse', 'Bexley Barnehurst',
       'Bexley Belvedere', 'Bexley Bexleyheath',
       'Bexley Blackfen & Lamorbey', 'Bexley Blendon & Penhill',
       'Bexley Crayford', 'Bexley Crook Log', 'Bexley East Wickham',
       'Bexley Erith', 'Bexley Falconwood & Welling', 'Bexley Longlands',
       'Bexley Northumberland Heath', 'Bexley Sidcup',
       'Bexley Slade Green & Northend', 'Bexley St Marys & St James',
       'Bexley Thamesmead East', 'Bexley West Heath', 'Brent Alperton',
       'Brent Barnhill', 'Brent Brondesbury Park',
       'Brent Cricklewood & Mapesbury', 'Brent Dollis Hill',
       'Brent Harlesden & Kensal Green', 'Brent Kenton', 'Brent Kilburn',
       'Brent Kingsbury', 'Brent Northwick Park', 'Brent Preston',
       'Brent Queens Park', 'Brent Queensbury', 'Brent Roundwood',
       'Brent Stonebridge', 'Brent Sudbury', 'Brent Tokyngton',
       'Brent Welsh Harp', 'Brent Wembley Central', 'Brent Wembley Hill',
       'Brent Wembley Park', 'Brent Willesden Green',
       'Bromley Beckenham Town & Copers Cope',
       'Bromley Bickley & Sundridge', 'Bromley Biggin Hill',
       'Bromley Bromley Common & Holwood', 'Bromley Bromley Town',
       'Bromley Chelsfield', 'Bromley Chislehurst', 'Bromley Clock House',
       'Bromley Crystal Palace & Anerley', 'Bromley Darwin',
       'Bromley Farnborough & Crofton', 'Bromley Hayes & Coney Hall',
       'Bromley Kelsey & Eden Park', 'Bromley Mottingham',
       'Bromley Orpington', 'Bromley Penge & Cator',
       'Bromley Petts Wood & Knoll', 'Bromley Plaistow',
       'Bromley Shortlands & Park Langley', 'Bromley St Mary Cray',
       'Bromley St Pauls Cray', 'Bromley West Wickham', 'Camden Belsize',
       'Camden Bloomsbury', 'Camden Camden Square', 'Camden Camden Town',
       'Camden Fortune Green', 'Camden Frognal', 'Camden Gospel Oak',
       'Camden Hampstead Town', 'Camden Haverstock', 'Camden Highgate',
       'Camden Holborn & Covent Garden', 'Camden Kentish Town North',
       'Camden Kentish Town South', 'Camden Kilburn',
       'Camden Kings Cross', 'Camden Primrose Hill',
       'Camden Regents Park', 'Camden South Hampstead',
       'Camden St Pancras & Somers Town', 'Camden West Hampstead',
       'Croydon Addiscombe East', 'Croydon Addiscombe West',
       'Croydon Bensham Manor', 'Croydon Broad Green',
       'Croydon Coulsdon Town', 'Croydon Crystal Palace & Upper Norwood',
       'Croydon Fairfield', 'Croydon Kenley',
       'Croydon New Addington North', 'Croydon New Addington South',
       'Croydon Norbury & Pollards Hill', 'Croydon Norbury Park',
       'Croydon Old Coulsdon', 'Croydon Park Hill & Whitgift',
       'Croydon Purley & Woodcote', 'Croydon Sanderstead',
       'Croydon Selhurst', 'Croydon Selsdon & Addington Village',
       'Croydon Selsdon Vale & Forestdale', 'Croydon Shirley North',
       'Croydon Shirley South', 'Croydon South Croydon',
       'Croydon South Norwood', 'Croydon Waddon', 'Croydon West Thornton',
       'Croydon Purley Oaks & Riddlesdown', 'Croydon Woodside',
       'Ealing Central Greenford', 'Ealing Dormers Wells',
       'Ealing Ealing Broadway', 'Ealing Ealing Common',
       'Ealing East Acton', 'Ealing Greenford Broadway',
       'Croydon Thornton Heath', 'Ealing Hanger Hill',
       'Ealing Hanwell Broadway', 'Ealing Lady Margaret',
       'Ealing North Acton', 'Ealing North Greenford',
       'Ealing North Hanwell', 'Ealing Northfield',
       'Ealing Northolt Mandeville', 'Ealing Northolt West End',
       'Ealing Norwood Green', 'Ealing Perivale', 'Ealing Pitshanger',
       'Ealing South Acton', 'Ealing Southall Broadway',
       'Ealing Southall Green', 'Ealing Southall West',
       'Ealing Southfield', 'Ealing Walpole', 'Enfield Arnos Grove',
       'Enfield Bowes', 'Enfield Brimsdown', 'Enfield Bullsmoor',
       'Enfield Bush Hill Park', 'Enfield Carterhatch',
       'Enfield Cockfosters', 'Enfield Edmonton Green',
       'Enfield Enfield Lock', 'Enfield Grange Park', 'Enfield Haselbury',
       'Enfield Highfield', 'Enfield Jubilee', 'Enfield Lower Edmonton',
       'Enfield New Southgate', 'Enfield Oakwood',
       'Enfield Palmers Green', 'Enfield Ponders End', 'Enfield Ridgeway',
       'Enfield Southbury', 'Enfield Southgate', 'Enfield Town',
       'Enfield Upper Edmonton', 'Enfield Whitewebbs',
       'Enfield Winchmore Hill', 'Greenwich Abbey Wood',
       'Greenwich Blackheath Westcombe', 'Greenwich Charlton Hornfair',
       'Greenwich Charlton Village & Riverside',
       'Greenwich East Greenwich', 'Greenwich Eltham Page',
       'Greenwich Eltham Park & Progress',
       'Greenwich Eltham Town & Avery Hill',
       'Greenwich Greenwich Creekside', 'Greenwich Greenwich Park',
       'Greenwich Greenwich Peninsula', 'Greenwich Kidbrooke Park',
       'Greenwich Kidbrooke Village & Sutcliffe',
       'Greenwich Middle Park & Horn Park',
       'Greenwich Mottingham Coldharbour & New Eltham',
       'Greenwich Plumstead & Glyndon', 'Greenwich Plumstead Common',
       'Greenwich Shooters Hill', 'Greenwich Thamesmead Moorings',
       'Greenwich West Thamesmead', 'Greenwich Woolwich Arsenal',
       'Greenwich Woolwich Common', 'Greenwich Woolwich Dockyard',
       'Hackney Brownswood', 'Hackney Cazenove', 'Hackney Clissold',
       'Hackney Dalston', 'Hackney De Beauvoir',
       'Hackney Hackney Central', 'Hackney Hackney Downs',
       'Hackney Hackney Wick', 'Hackney Haggerston', 'Hackney Homerton',
       'Hackney Hoxton East & Shoreditch', 'Hackney Hoxton West',
       'Hackney Kings Park', 'Hackney London Fields',
       'Hackney Shacklewell', 'Hackney Springfield',
       'Hackney Stamford Hill West', 'Hackney Stoke Newington',
       'Hackney Victoria', 'Hackney Woodberry Down', 'Hackney Lea Bridge',
       'Hammersmith and Fulham Addison',
       'Hammersmith and Fulham Avonmore',
       'Hammersmith and Fulham Brook Green',
       'Hammersmith and Fulham College Park & Old Oak',
       'Hammersmith and Fulham Coningham',
       'Hammersmith and Fulham Fulham Reach',
       'Hammersmith and Fulham Fulham Town',
       'Hammersmith and Fulham Grove',
       'Hammersmith and Fulham Hammersmith Broadway',
       'Hammersmith and Fulham Lillie', 'Hammersmith and Fulham Munster',
       'Hammersmith and Fulham Palace & Hurlingham',
       'Hammersmith and Fulham Parsons Green & Sandford',
       'Hammersmith and Fulham Ravenscourt',
       'Hammersmith and Fulham Sands End',
       'Hammersmith and Fulham Shepherds Bush Green',
       'Hammersmith and Fulham Walham Green',
       'Hammersmith and Fulham Wendell Park',
       'Hammersmith and Fulham West Kensington',
       'Hammersmith and Fulham White City',
       'Hammersmith and Fulham Wormholt', 'Haringey Alexandra Park',
       'Haringey Bounds Green', 'Haringey Bruce Castle',
       'Haringey Crouch End', 'Haringey Fortis Green',
       'Haringey Harringay', 'Haringey Hermitage & Gardens',
       'Haringey Highgate', 'Haringey Hornsey', 'Haringey Muswell Hill',
       'Haringey Noel Park', 'Haringey Northumberland Park',
       'Haringey Seven Sisters', 'Haringey South Tottenham',
       'Haringey St Anns', 'Haringey Stroud Green',
       'Haringey Tottenham Central', 'Haringey Tottenham Hale',
       'Haringey West Green', 'Haringey White Hart Lane',
       'Haringey Woodside', 'Harrow Belmont', 'Harrow Canons',
       'Harrow Centenary', 'Harrow Edgware', 'Harrow Greenhill',
       'Harrow Harrow on the Hill', 'Harrow Harrow Weald',
       'Harrow Hatch End', 'Harrow Headstone', 'Harrow Kenton West',
       'Harrow Marlborough', 'Harrow North Harrow', 'Harrow Pinner',
       'Harrow Pinner South', 'Harrow Rayners Lane', 'Harrow Roxeth',
       'Harrow Stanmore', 'Harrow Wealdstone North',
       'Harrow Wealdstone South', 'Harrow West Harrow',
       'Havering Beam Park', 'Harrow Kenton East', 'Havering Cranham',
       'Havering Elm Park', 'Havering Emerson Park', 'Havering Gooshays',
       'Harrow Roxbourne', 'Havering Hacton', 'Havering Harold Wood',
       'Havering Havering-atte-Bower', 'Havering Heaton',
       'Havering Hylands & Harrow Lodge',
       'Havering Marshalls & Rise Park', 'Havering Mawneys',
       'Havering Rainham & Wennington', 'Havering Rush Green & Crowlands',
       'Havering South Hornchurch', 'Havering Squirrels Heath',
       'Havering St Albans', 'Havering St Andrews', 'Havering Upminster',
       'Hillingdon Belmore', 'Hillingdon Charville',
       'Havering St Edwards', 'Hillingdon Colham & Cowley',
       'Hillingdon Eastcote', 'Hillingdon Harefield Village',
       'Hillingdon Hayes Town', 'Hillingdon Heathrow Villages',
       'Hillingdon Hillingdon East',
       'Hillingdon Ickenham & South Harefield', 'Hillingdon Northwood',
       'Hillingdon Northwood Hills', 'Hillingdon Pinkwell',
       'Hillingdon Ruislip', 'Hillingdon Ruislip Manor',
       'Hillingdon South Ruislip', 'Hillingdon Uxbridge',
       'Hillingdon West Drayton', 'Hillingdon Hillingdon West',
       'Hillingdon Wood End', 'Hillingdon Yeading', 'Hillingdon Yiewsley',
       'Hounslow Bedfont', 'Hounslow Brentford East',
       'Hounslow Brentford West', 'Hounslow Chiswick Gunnersbury',
       'Hounslow Chiswick Homefields', 'Hounslow Chiswick Riverside',
       'Hounslow Cranford', 'Hounslow Feltham North',
       'Hounslow Feltham West', 'Hounslow Hanworth Park',
       'Hounslow Hanworth Village', 'Hounslow Heston Central',
       'Hounslow Heston East', 'Hounslow Heston West',
       'Hounslow Hounslow Central', 'Hounslow Hounslow East',
       'Hounslow Hounslow Heath', 'Hounslow Hounslow South',
       'Hounslow Hounslow West', 'Hounslow Isleworth',
       'Hounslow Osterley & Spring Grove',
       'Hounslow Syon & Brentford Lock', 'Islington Arsenal',
       'Islington Barnsbury', 'Islington Bunhill', 'Islington Caledonian',
       'Islington Canonbury', 'Islington Clerkenwell',
       'Islington Finsbury Park', 'Islington Highbury',
       'Islington Hillrise', 'Islington Holloway', 'Islington Junction',
       'Islington Laycock', 'Islington Mildmay',
       'Islington St Marys & St James', 'Islington St Peters & Canalside',
       'Islington Tollington', 'Islington Tufnell Park',
       'Kensington and Chelsea Abingdon',
       'Kensington and Chelsea Brompton & Hans Town',
       'Kensington and Chelsea Campden',
       'Kensington and Chelsea Chelsea Riverside',
       'Kensington and Chelsea Colville',
       'Kensington and Chelsea Courtfield',
       'Kensington and Chelsea Dalgarno',
       'Kensington and Chelsea Earls Court',
       'Kensington and Chelsea Golborne',
       'Kensington and Chelsea Holland', 'Kensington and Chelsea Norland',
       'Kensington and Chelsea Notting Dale',
       'Kensington and Chelsea Pembridge',
       'Kensington and Chelsea Queens Gate',
       'Kensington and Chelsea Redcliffe',
       'Kensington and Chelsea Royal Hospital',
       'Kensington and Chelsea St Helens',
       'Kensington and Chelsea Stanley', 'Kingston upon Thames Alexandra',
       'Kingston upon Thames Berrylands',
       'Kingston upon Thames Canbury Gardens',
       'Kingston upon Thames Chessington South & Malden Rushett',
       'Kingston upon Thames Coombe Hill',
       'Kingston upon Thames Coombe Vale',
       'Kingston upon Thames Green Lane & St James',
       'Kingston upon Thames Hook & Chessington North',
       'Kingston upon Thames King Georges & Sunray',
       'Kingston upon Thames Kingston Gate',
       'Kingston upon Thames Kingston Town',
       'Kingston upon Thames Motspur Park & Old Malden East',
       'Kingston upon Thames New Malden Village',
       'Kingston upon Thames Norbiton', 'Kingston upon Thames Old Malden',
       'Kingston upon Thames St Marks & Seething Wells',
       'Kingston upon Thames Surbiton Hill',
       'Kingston upon Thames Tolworth', 'Kingston upon Thames Tudor',
       'Lambeth Brixton Acre Lane', 'Lambeth Brixton North',
       'Lambeth Brixton Rush Common', 'Lambeth Brixton Windrush',
       'Lambeth Clapham Common & Abbeville', 'Lambeth Clapham East',
       'Lambeth Clapham Park', 'Lambeth Clapham Town',
       'Lambeth Gipsy Hill', 'Lambeth Herne Hill & Loughborough Junction',
       'Lambeth Kennington', 'Lambeth Knights Hill',
       'Lambeth Myatts Fields', 'Lambeth Oval', 'Lambeth St Martins',
       'Lambeth Stockwell East', 'Lambeth Stockwell West & Larkhall',
       'Lambeth Streatham Common & Vale', 'Lambeth Streatham Hill East',
       'Lambeth Streatham Hill West & Thornton',
       'Lambeth Streatham St Leonards', 'Lambeth Streatham Wells',
       'Lambeth Vauxhall', 'Lambeth Waterloo & South Bank',
       'Lambeth West Dulwich', 'Lewisham Bellingham',
       'Lewisham Blackheath', 'Lewisham Brockley',
       'Lewisham Catford South', 'Lewisham Crofton Park',
       'Lewisham Deptford', 'Lewisham Downham', 'Lewisham Evelyn',
       'Lewisham Forest Hill', 'Lewisham Grove Park',
       'Lewisham Hither Green', 'Lewisham Ladywell', 'Lewisham Lee Green',
       'Lewisham Lewisham Central', 'Lewisham New Cross Gate',
       'Lewisham Perry Vale', 'Lewisham Rushey Green',
       'Lewisham Sydenham', 'Lewisham Telegraph Hill', 'Merton Abbey',
       'Merton Cannon Hill', 'Merton Colliers Wood',
       'Merton Cricket Green', 'Merton Figges Marsh', 'Merton Graveney',
       'Merton Hillside', 'Merton Lavender Fields', 'Merton Longthornton',
       'Merton Lower Morden', 'Merton Merton Park',
       'Merton Pollards Hill', 'Merton Ravensbury', 'Merton Raynes Park',
       'Merton St Helier', 'Merton Village', 'Merton Wandle',
       'Merton West Barnes', 'Merton Wimbledon Park',
       'Merton Wimbledon Town & Dundonald', 'Newham Beckton',
       'Newham Boleyn', 'Newham Canning Town North',
       'Newham Canning Town South', 'Newham Custom House',
       'Newham East Ham', 'Newham East Ham South',
       'Newham Forest Gate North', 'Newham Forest Gate South',
       'Newham Green Street East', 'Newham Green Street West',
       'Newham Little Ilford', 'Newham Manor Park', 'Newham Maryland',
       'Newham Plaistow North', 'Newham Plaistow South',
       'Newham Plaistow West & Canning Town East', 'Newham Plashet',
       'Newham Royal Albert', 'Newham Royal Victoria', 'Newham Stratford',
       'Newham Wall End', 'Newham West Ham',
       'Newham Stratford Olympic Park', 'Redbridge Aldborough',
       'Redbridge Barkingside', 'Redbridge Bridge', 'Redbridge Chadwell',
       'Redbridge Churchfields', 'Redbridge Clayhall',
       'Redbridge Clementswood', 'Redbridge Cranbrook',
       'Redbridge Fairlop', 'Redbridge Fullwell', 'Redbridge Goodmayes',
       'Redbridge Hainault', 'Redbridge Ilford Town', 'Redbridge Loxford',
       'Redbridge Mayfield', 'Redbridge Monkhams', 'Redbridge Newbury',
       'Redbridge Seven Kings', 'Redbridge South Woodford',
       'Redbridge Valentines', 'Redbridge Wanstead Park',
       'Redbridge Wanstead Village', 'Richmond upon Thames Barnes',
       'Richmond upon Thames East Sheen',
       'Richmond upon Thames Fulwell & Hampton Hill',
       'Richmond upon Thames Ham Petersham & Richmond Riverside',
       'Richmond upon Thames Hampton',
       'Richmond upon Thames Hampton North',
       'Richmond upon Thames Hampton Wick & South Teddington',
       'Richmond upon Thames Heathfield', 'Richmond upon Thames Kew',
       'Richmond upon Thames Mortlake & Barnes Common',
       'Richmond upon Thames North Richmond',
       'Richmond upon Thames South Richmond',
       'Richmond upon Thames South Twickenham',
       'Richmond upon Thames St Margarets & North Twickenham',
       'Richmond upon Thames Teddington',
       'Richmond upon Thames Twickenham Riverside',
       'Richmond upon Thames West Twickenham',
       'Richmond upon Thames Whitton', 'Southwark Borough & Bankside',
       'Southwark Camberwell Green', 'Southwark Champion Hill',
       'Southwark Chaucer', 'Southwark Dulwich Hill',
       'Southwark Dulwich Village', 'Southwark Dulwich Wood',
       'Southwark Faraday', 'Southwark Goose Green',
       'Southwark London Bridge & West Bermondsey',
       'Southwark North Bermondsey', 'Southwark North Walworth',
       'Southwark Nunhead & Queens Road', 'Southwark Old Kent Road',
       'Southwark Peckham', 'Southwark Newington',
       'Southwark Peckham Rye', 'Southwark Rotherhithe',
       'Southwark Rye Lane', 'Southwark South Bermondsey',
       'Southwark St Georges', 'Southwark St Giles',
       'Southwark Surrey Docks', 'Sutton Beddington', 'Sutton Belmont',
       'Sutton Carshalton Central',
       'Sutton Carshalton South & Clockhouse', 'Sutton Cheam',
       'Sutton Hackbridge', 'Sutton North Cheam',
       'Sutton South Beddington & Roundshaw', 'Sutton St Helier East',
       'Sutton St Helier West', 'Sutton Stonecot',
       'Sutton Sutton Central', 'Sutton Sutton North',
       'Sutton Sutton South', 'Sutton Sutton West & East Cheam',
       'Sutton The Wrythe', 'Sutton Wallington North',
       'Sutton Wallington South', 'Sutton Worcester Park South',
       'Tower Hamlets Bethnal Green East',
       'Tower Hamlets Bethnal Green West',
       'Tower Hamlets Blackwall & Cubitt Town', 'Tower Hamlets Bow East',
       'Tower Hamlets Bow West', 'Tower Hamlets Bromley North',
       'Tower Hamlets Bromley South', 'Tower Hamlets Canary Wharf',
       'Tower Hamlets Island Gardens', 'Tower Hamlets Lansbury',
       'Tower Hamlets Limehouse', 'Tower Hamlets Mile End',
       'Tower Hamlets Poplar', 'Tower Hamlets Shadwell',
       'Sutton Worcester Park North',
       'Tower Hamlets Spitalfields & Banglatown',
       'Tower Hamlets St Dunstans',
       'Tower Hamlets St Katharines & Wapping',
       'Tower Hamlets Stepney Green', 'Tower Hamlets Weavers',
       'Tower Hamlets Whitechapel', 'Waltham Forest Cann Hall',
       'Waltham Forest Cathall', 'Waltham Forest Chapel End',
       'Waltham Forest Chingford Green', 'Waltham Forest Endlebury',
       'Waltham Forest Forest', 'Waltham Forest Grove Green',
       'Waltham Forest Hatch Lane & Highams Park North',
       'Waltham Forest High Street', 'Waltham Forest Higham Hill',

In [59]:
df['Area name'].unique()

array(['Barking and Dagenham', 'Barnet', 'Bexley', 'Brent', 'Bromley',
       'Camden', 'Croydon', 'Ealing', 'Enfield', 'Greenwich', 'Hackney',
       'Hammersmith and Fulham', 'Haringey', 'Harrow', 'Havering',
       'Hillingdon', 'Hounslow', 'Islington', 'Kensington and Chelsea',
       'Kingston upon Thames', 'Lambeth', 'Lewisham', 'Merton',
       'Other / NK', 'Newham', 'Redbridge', 'Richmond upon Thames',
       'Southwark', 'Sutton', 'Tower Hamlets', 'Waltham Forest',
       'Wandsworth', 'Westminster', 'Abbey', 'Alibon',
       'Barking Riverside', 'Beam', 'Becontree', 'Chadwell Heath',
       'Eastbrook & Rush Green', 'Eastbury', 'Gascoigne', 'Goresbrook',
       'Heath', 'Longbridge', 'Mayesbrook', 'Northbury', 'Parsloes',
       'Thames View', 'Valence', 'Village', 'Whalebone', 'Barnet Vale',
       'Brunswick Park', 'Burnt Oak', 'Childs Hill', 'Colindale North',
       'Colindale South', 'Cricklewood', 'East Barnet', 'East Finchley',
       'Edgware', 'Edgwarebury', 'Finchley Church End', 'Friern Barnet',
       'Garden Suburb', 'Golders Green', 'Hendon', 'High Barnet',
       'Mill Hill', 'Totteridge & Woodside', 'Underhill', 'West Finchley',
       'West Hendon', 'Whetstone', 'Woodhouse', 'Barnehurst', 'Belvedere',
       'Bexleyheath', 'Blackfen & Lamorbey', 'Blendon & Penhill',
       'Crayford', 'Crook Log', 'East Wickham', 'Erith',
       'Falconwood & Welling', 'Longlands', 'Northumberland Heath',
       'Sidcup', 'Slade Green & Northend', 'St Marys & St James',
       'Thamesmead East', 'West Heath', 'Alperton', 'Barnhill',
       'Brondesbury Park', 'Cricklewood & Mapesbury', 'Dollis Hill',
       'Harlesden & Kensal Green', 'Kenton', 'Kilburn', 'Kingsbury',
       'Northwick Park', 'Preston', 'Queens Park', 'Queensbury',
       'Roundwood', 'Stonebridge', 'Sudbury', 'Tokyngton', 'Welsh Harp',
       'Wembley Central', 'Wembley Hill', 'Wembley Park',
       'Willesden Green', 'Beckenham Town & Copers Cope',
       'Bickley & Sundridge', 'Biggin Hill', 'Bromley Common & Holwood',
       'Bromley Town', 'Chelsfield', 'Chislehurst', 'Clock House',
       'Crystal Palace & Anerley', 'Darwin', 'Farnborough & Crofton',
       'Hayes & Coney Hall', 'Kelsey & Eden Park', 'Mottingham',
       'Orpington', 'Penge & Cator', 'Petts Wood & Knoll', 'Plaistow',
       'Shortlands & Park Langley', 'St Mary Cray', 'St Pauls Cray',
       'West Wickham', 'Belsize', 'Bloomsbury', 'Camden Square',
       'Camden Town', 'Fortune Green', 'Frognal', 'Gospel Oak',
       'Hampstead Town', 'Haverstock', 'Highgate',
       'Holborn & Covent Garden', 'Kentish Town North',
       'Kentish Town South', 'Kings Cross', 'Primrose Hill',
       'Regents Park', 'South Hampstead', 'St Pancras & Somers Town',
       'West Hampstead', 'Addiscombe East', 'Addiscombe West',
       'Bensham Manor', 'Broad Green', 'Coulsdon Town',
       'Crystal Palace & Upper Norwood', 'Fairfield', 'Kenley',
       'New Addington North', 'New Addington South',
       'Norbury & Pollards Hill', 'Norbury Park', 'Old Coulsdon',
       'Park Hill & Whitgift', 'Purley & Woodcote', 'Sanderstead',
       'Selhurst', 'Selsdon & Addington Village',
       'Selsdon Vale & Forestdale', 'Shirley North', 'Shirley South',
       'South Croydon', 'South Norwood', 'Waddon', 'West Thornton',
       'Purley Oaks & Riddlesdown', 'Woodside', 'Central Greenford',
       'Dormers Wells', 'Ealing Broadway', 'Ealing Common', 'East Acton',
       'Greenford Broadway', 'Thornton Heath', 'Hanger Hill',
       'Hanwell Broadway', 'Lady Margaret', 'North Acton',
       'North Greenford', 'North Hanwell', 'Northfield',
       'Northolt Mandeville', 'Northolt West End', 'Norwood Green',
       'Perivale', 'Pitshanger', 'South Acton', 'Southall Broadway',
       'Southall Green', 'Southall West', 'Southfield', 'Walpole',
       'Arnos Grove', 'Bowes', 'Brimsdown', 'Bullsmoor', 'Bush Hill Park',
       'Carterhatch', 'Cockfosters', 'Edmonton Green', 'Enfield Lock',
       'Grange Park', 'Haselbury', 'Highfield', 'Jubilee',
       'Lower Edmonton', 'New Southgate', 'Oakwood', 'Palmers Green',
       'Ponders End', 'Ridgeway', 'Southbury', 'Southgate', 'Town',
       'Upper Edmonton', 'Whitewebbs', 'Winchmore Hill', 'Abbey Wood',
       'Blackheath Westcombe', 'Charlton Hornfair',
       'Charlton Village & Riverside', 'East Greenwich', 'Eltham Page',
       'Eltham Park & Progress', 'Eltham Town & Avery Hill',
       'Greenwich Creekside', 'Greenwich Park', 'Greenwich Peninsula',
       'Kidbrooke Park', 'Kidbrooke Village & Sutcliffe',
       'Middle Park & Horn Park', 'Mottingham, Coldharbour & New Eltham',
       'Plumstead & Glyndon', 'Plumstead Common', 'Shooters Hill',
       'Thamesmead Moorings', 'West Thamesmead', 'Woolwich Arsenal',
       'Woolwich Common', 'Woolwich Dockyard', 'Brownswood', 'Cazenove',
       'Clissold', 'Dalston', 'De Beauvoir', 'Hackney Central',
       'Hackney Downs', 'Hackney Wick', 'Haggerston', 'Homerton',
       'Hoxton East & Shoreditch', 'Hoxton West', 'Kings Park',
       'London Fields', 'Shacklewell', 'Springfield',
       'Stamford Hill West', 'Stoke Newington', 'Victoria',
       'Woodberry Down', 'Lea Bridge', 'Addison', 'Avonmore',
       'Brook Green', 'College Park & Old Oak', 'Coningham',
       'Fulham Reach', 'Fulham Town', 'Grove', 'Hammersmith Broadway',
       'Lillie', 'Munster', 'Palace & Hurlingham',
       'Parsons Green & Sandford', 'Ravenscourt', 'Sands End',
       'Shepherds Bush Green', 'Walham Green', 'Wendell Park',
       'West Kensington', 'White City', 'Wormholt', 'Alexandra Park',
       'Bounds Green', 'Bruce Castle', 'Crouch End', 'Fortis Green',
       'Harringay', 'Hermitage & Gardens', 'Hornsey', 'Muswell Hill',
       'Noel Park', 'Northumberland Park', 'Seven Sisters',
       'South Tottenham', 'St Anns', 'Stroud Green', 'Tottenham Central',
       'Tottenham Hale', 'West Green', 'White Hart Lane', 'Belmont',
       'Canons', 'Centenary', 'Greenhill', 'Harrow on the Hill',
       'Harrow Weald', 'Hatch End', 'Headstone', 'Kenton West',
       'Marlborough', 'North Harrow', 'Pinner', 'Pinner South',
       'Rayners Lane', 'Roxeth', 'Stanmore', 'Wealdstone North',
       'Wealdstone South', 'West Harrow', 'Beam Park', 'Kenton East',
       'Cranham', 'Elm Park', 'Emerson Park', 'Gooshays', 'Roxbourne',
       'Hacton', 'Harold Wood', 'Havering-atte-Bower', 'Heaton',
       'Hylands & Harrow Lodge', 'Marshalls & Rise Park', 'Mawneys',
       'Rainham & Wennington', 'Rush Green & Crowlands',
       'South Hornchurch', 'Squirrels Heath', 'St Albans', 'St Andrews',
       'Upminster', 'Belmore', 'Charville', 'St Edwards',
       'Colham & Cowley', 'Eastcote', 'Harefield Village', 'Hayes Town',
       'Heathrow Villages', 'Hillingdon East',
       'Ickenham & South Harefield', 'Northwood', 'Northwood Hills',
       'Pinkwell', 'Ruislip', 'Ruislip Manor', 'South Ruislip',
       'Uxbridge', 'West Drayton', 'Hillingdon West', 'Wood End',
       'Yeading', 'Yiewsley', 'Bedfont', 'Brentford East',
       'Brentford West', 'Chiswick Gunnersbury', 'Chiswick Homefields',
       'Chiswick Riverside', 'Cranford', 'Feltham North', 'Feltham West',
       'Hanworth Park', 'Hanworth Village', 'Heston Central',
       'Heston East', 'Heston West', 'Hounslow Central', 'Hounslow East',
       'Hounslow Heath', 'Hounslow South', 'Hounslow West', 'Isleworth',
       'Osterley & Spring Grove', 'Syon & Brentford Lock', 'Arsenal',
       'Barnsbury', 'Bunhill', 'Caledonian', 'Canonbury', 'Clerkenwell',
       'Finsbury Park', 'Highbury', 'Hillrise', 'Holloway', 'Junction',
       'Laycock', 'Mildmay', 'St Peters & Canalside', 'Tollington',
       'Tufnell Park', 'Abingdon', 'Brompton & Hans Town', 'Campden',
       'Chelsea Riverside', 'Colville', 'Courtfield', 'Dalgarno',
       'Earls Court', 'Golborne', 'Holland', 'Norland', 'Notting Dale',
       'Pembridge', 'Queens Gate', 'Redcliffe', 'Royal Hospital',
       'St Helens', 'Stanley', 'Alexandra', 'Berrylands',
       'Canbury Gardens', 'Chessington South & Malden Rushett',
       'Coombe Hill', 'Coombe Vale', 'Green Lane & St James',
       'Hook & Chessington North', 'King Georges & Sunray',
       'Kingston Gate', 'Kingston Town', 'Motspur Park & Old Malden East',
       'New Malden Village', 'Norbiton', 'Old Malden',
       'St Marks & Seething Wells', 'Surbiton Hill', 'Tolworth', 'Tudor',
       'Brixton Acre Lane', 'Brixton North', 'Brixton Rush Common',
       'Brixton Windrush', 'Clapham Common & Abbeville', 'Clapham East',
       'Clapham Park', 'Clapham Town', 'Gipsy Hill',
       'Herne Hill & Loughborough Junction', 'Kennington', 'Knights Hill',
       'Myatts Fields', 'Oval', 'St Martins', 'Stockwell East',
       'Stockwell West & Larkhall', 'Streatham Common & Vale',
       'Streatham Hill East', 'Streatham Hill West & Thornton',
       'Streatham St Leonards', 'Streatham Wells', 'Vauxhall',
       'Waterloo & South Bank', 'West Dulwich', 'Bellingham',
       'Blackheath', 'Brockley', 'Catford South', 'Crofton Park',
       'Deptford', 'Downham', 'Evelyn', 'Forest Hill', 'Grove Park',
       'Hither Green', 'Ladywell', 'Lee Green', 'Lewisham Central',
       'New Cross Gate', 'Perry Vale', 'Rushey Green', 'Sydenham',
       'Telegraph Hill', 'Cannon Hill', 'Colliers Wood', 'Cricket Green',
       'Figges Marsh', 'Graveney', 'Hillside', 'Lavender Fields',
       'Longthornton', 'Lower Morden', 'Merton Park', 'Pollards Hill',
       'Ravensbury', 'Raynes Park', 'St Helier', 'Wandle', 'West Barnes',
       'Wimbledon Park', 'Wimbledon Town & Dundonald', 'Beckton',
       'Boleyn', 'Canning Town North', 'Canning Town South',
       'Custom House', 'East Ham', 'East Ham South', 'Forest Gate North',
       'Forest Gate South', 'Green Street East', 'Green Street West',
       'Little Ilford', 'Manor Park', 'Maryland', 'Plaistow North',
       'Plaistow South', 'Plaistow West & Canning Town East', 'Plashet',
       'Royal Albert', 'Royal Victoria', 'Stratford', 'Wall End',
       'West Ham', 'Stratford Olympic Park', 'Aldborough', 'Barkingside',
       'Bridge', 'Chadwell', 'Churchfields', 'Clayhall', 'Clementswood',
       'Cranbrook', 'Fairlop', 'Fullwell', 'Goodmayes', 'Hainault',
       'Ilford Town', 'Loxford', 'Mayfield', 'Monkhams', 'Newbury',
       'Seven Kings', 'South Woodford', 'Valentines', 'Wanstead Park',
       'Wanstead Village', 'Barnes', 'East Sheen',
       'Fulwell & Hampton Hill', 'Ham, Petersham & Richmond Riverside',
       'Hampton', 'Hampton North', 'Hampton Wick & South Teddington',
       'Heathfield', 'Kew', 'Mortlake & Barnes Common', 'North Richmond',
       'South Richmond', 'South Twickenham',
       'St Margarets & North Twickenham', 'Teddington',
       'Twickenham Riverside', 'West Twickenham', 'Whitton',
       'Borough & Bankside', 'Camberwell Green', 'Champion Hill',
       'Chaucer', 'Dulwich Hill', 'Dulwich Village', 'Dulwich Wood',
       'Faraday', 'Goose Green', 'London Bridge & West Bermondsey',
       'North Bermondsey', 'North Walworth', 'Nunhead & Queens Road',
       'Old Kent Road', 'Peckham', 'Newington', 'Peckham Rye',
       'Rotherhithe', 'Rye Lane', 'South Bermondsey', 'St Georges',
       'St Giles', 'Surrey Docks', 'Beddington', 'Carshalton Central',
       'Carshalton South & Clockhouse', 'Cheam', 'Hackbridge',
       'North Cheam', 'South Beddington & Roundshaw', 'St Helier East',
       'St Helier West', 'Stonecot', 'Sutton Central', 'Sutton North',
       'Sutton South', 'Sutton West & East Cheam', 'The Wrythe',
       'Wallington North', 'Wallington South', 'Worcester Park South',
       'Bethnal Green East', 'Bethnal Green West',
       'Blackwall & Cubitt Town', 'Bow East', 'Bow West', 'Bromley North',
       'Bromley South', 'Canary Wharf', 'Island Gardens', 'Lansbury',
       'Limehouse', 'Mile End', 'Poplar', 'Shadwell',
       'Worcester Park North', 'Spitalfields & Banglatown', 'St Dunstans',
       'St Katharines & Wapping', 'Stepney Green', 'Weavers',
       'Whitechapel', 'Cann Hall', 'Cathall', 'Chapel End',
       'Chingford Green', 'Endlebury', 'Forest', 'Grove Green',
       'Hatch Lane & Highams Park North', 'High Street', 'Higham Hill',
       'Hoe Street', 'Larkswood', 'Leyton', 'Leytonstone', 'Markhouse',
       'St James', 'Upper Walthamstow', 'Valley', 'William Morris',
       'Wood Street', 'Balham', 'Battersea Park', 'East Putney',
       'Falconbrook', 'Furzedown', 'Lavender', 'Nine Elms', 'Northcote',
       'Hale End & Highams Park South', 'Roehampton',
       'Shaftesbury & Queenstown', 'South Balham', 'Southfields',
       'St Marys', 'Tooting Bec', 'Tooting Broadway', 'Trinity',
       'Wandsworth Common', 'Wandsworth Town', 'West Hill', 'West Putney',
       'Abbey Road', 'Bayswater', 'Church Street', 'Harrow Road',
       'Hyde Park', 'Knightsbridge & Belgravia', 'Lancaster Gate',
       'Little Venice', 'Maida Vale', 'Marylebone', 'Pimlico North',
       'Pimlico South', 'St Jamess', 'Thamesfield', 'Vincent Square',
       'West End', 'Westbourne', 'Village (KG)', 'Colindale (NOT ACTIVE)',
       'Kilburn (QK)', 'Highgate (EK)', 'Regents Park (EK)', 'Abbey (KG)',
       'Edgware (SX)', 'Fairfield (Croydon)', 'Woodside (Croydon)',
       'Wandle (VW)', 'Lea Bridge (Hackney)', nan, 'Belmont (QA)',
       'Brunel (NOT ACTIVE)', 'Heathrow Villages (NOT ACTIVE)',
       'West End (NOT ACTIVE)', 'Northwood (NOT ACTIVE)',
       'St Leonards (NOT ACTIVE)', 'Lewisham Central (NOT ACTIVE)',
       'Unknown', 'Ealing Broadway (NOT ACTIVE)',
       'Kentish Town (NOT ACTIVE)', 'Grove Green (NOT ACTIVE)',
       'Alperton (NOT ACTIVE)', 'Hounslow Central (NOT ACTIVE)',
       'Clapham Town (NOT ACTIVE)',
       'St Pancras & Somers Town (NOT ACTIVE)',
       'Vincent Square (NOT ACTIVE)', 'Acton Central (NOT ACTIVE)'],
      dtype=object)

In [77]:
df['Borough_SNT'].nunique(), df['Area name'].nunique()

(720, 728)

In [147]:
df[df['Area name'].isnull()]['Borough_SNT'].head()

448908    Other / NK
448911    Other / NK
452077    Other / NK
452078    Other / NK
452082    Other / NK
Name: Borough_SNT, dtype: object

In [133]:
df[df['Borough_SNT'] == 'N/K' ]['Area name'].unique()

array(['Other / NK'], dtype=object)

In [131]:
df['Area name'].isnull().sum()

625

In [149]:
# 625 area values are null, where Borough_SNT is OTHER / NK

In [151]:
df[df['Area name'].isnull()].head()

,Month_Year,Area Type,Borough_SNT,Area name,Area code,Offence Group,Offence Subgroup,Measure,Financial Year,FY_FYIndex,Count,Refresh Date
448908,2024-02-01,Safer Neighbourhood Teams,Other / NK,NaN,-1,VIOLENCE AGAINST THE PERSON,VIOLENCE WITH INJURY,Offences,fy23-24,23-24_01,8,2025-06-05
448911,2024-02-01,Safer Neighbourhood Teams,Other / NK,NaN,-1,VIOLENCE AGAINST THE PERSON,VIOLENCE WITHOUT INJURY,Offences,fy23-24,23-24_01,17,2025-06-05
452077,2024-02-01,Safer Neighbourhood Teams,Other / NK,NaN,-1,PUBLIC ORDER OFFENCES,RACE OR RELIGIOUS AGG PUBLIC FEAR,Offences,fy23-24,23-24_01,1,2025-06-05
452078,2024-02-01,Safer Neighbourhood Teams,Other / NK,NaN,-1,SEXUAL OFFENCES,OTHER SEXUAL OFFENCES,Offences,fy23-24,23-24_01,2,2025-06-05
452082,2024-02-01,Safer Neighbourhood Teams,Other / NK,NaN,-1,THEFT,BICYCLE THEFT,Offences,fy23-24,23-24_01,8,2025-06-05

In [179]:
df[df['Area name']=='Other / NK']['Borough_SNT'].unique()

array(['N/K', 'Other / NK', 'Aviation Security'], dtype=object)

In [187]:
# Same values of "Borough_SNT" is filled where "Area name" is null because it contain "Other / NK" value only

In [181]:
df['Area name'] = df['Area name'].fillna(df['Borough_SNT'])

In [185]:
df.isnull().sum()

Month_Year             0
Area Type              0
Borough_SNT            0
Area name              0
Area code           3219
Offence Group          0
Offence Subgroup       0
Measure                0
Financial Year         0
FY_FYIndex             0
Count                  0
Refresh Date           0
dtype: int64

In [203]:
df['Area code'].unique()

array(['E09000002', 'E09000003', 'E09000004', 'E09000005', 'E09000006',
       'E09000007', 'E09000008', 'E09000009', 'E09000010', 'E09000011',
       'E09000012', 'E09000013', 'E09000014', 'E09000015', 'E09000016',
       'E09000017', 'E09000018', 'E09000019', 'E09000020', 'E09000021',
       'E09000022', 'E09000023', 'E09000024', nan, 'E09000025',
       'E09000026', 'E09000027', 'E09000028', 'E09000029', 'E09000030',
       'E09000031', 'E09000032', 'E09000033', 'E05014053', 'E05014054',
       'E05014055', 'E05014056', 'E05014057', 'E05014058', 'E05014059',
       'E05014060', 'E05014061', 'E05014062', 'E05014063', 'E05014064',
       'E05014065', 'E05014066', 'E05014067', 'E05014068', 'E05014069',
       'E05014070', 'E05014071', 'E05013628', 'E05013629', 'E05013630',
       'E05013631', 'E05013632', 'E05013633', 'E05013634', 'E05013635',
       'E05013636', 'E05013637', 'E05013638', 'E05013639', 'E05013640',
       'E05013641', 'E05013642', 'E05013643', 'E05013644', 'E05013645',
       'E05013646', 'E05013647', 'E05013648', 'E05013649', 'E05013650',
       'E05013651', 'E05011217', 'E05011218', 'E05011219', 'E05011220',
       'E05011221', 'E05011222', 'E05011223', 'E05011224', 'E05011225',
       'E05011226', 'E05011227', 'E05011228', 'E05011230', 'E05011231',
       'E05011229', 'E05011232', 'E05011233', 'E05013496', 'E05013497',
       'E05013498', 'E05013499', 'E05013500', 'E05013501', 'E05013502',
       'E05013503', 'E05013504', 'E05013505', 'E05013506', 'E05013507',
       'E05013508', 'E05013509', 'E05013510', 'E05013511', 'E05013512',
       'E05013513', 'E05013514', 'E05013515', 'E05013516', 'E05013517',
       'E05013987', 'E05013988', 'E05013989', 'E05013990', 'E05013991',
       'E05013992', 'E05013993', 'E05013994', 'E05013995', 'E05013996',
       'E05013997', 'E05013998', 'E05013999', 'E05014000', 'E05014001',
       'E05014002', 'E05014003', 'E05014004', 'E05014005', 'E05014006',
       'E05014007', 'E05014008', 'E05013652', 'E05013653', 'E05013654',
       'E05013655', 'E05013656', 'E05013657', 'E05013658', 'E05013659',
       'E05013660', 'E05013661', 'E05013662', 'E05013663', 'E05013664',
       'E05013665', 'E05013666', 'E05013667', 'E05013668', 'E05013670',
       'E05013669', 'E05013671', 'E05011462', 'E05011463', 'E05011464',
       'E05011465', 'E05011466', 'E05011467', 'E05011468', 'E05011469',
       'E05011470', 'E05011471', 'E05011472', 'E05011473', 'E05011474',
       'E05011475', 'E05011476', 'E05011478', 'E05011479', 'E05011480',
       'E05011481', 'E05011482', 'E05011483', 'E05011484', 'E05011485',
       'E05011487', 'E05011488', 'E05011477', 'E05011489', 'E05013518',
       'E05013519', 'E05013520', 'E05013521', 'E05013522', 'E05013523',
       'E05011486', 'E05013524', 'E05013525', 'E05013526', 'E05013527',
       'E05013528', 'E05013529', 'E05013530', 'E05013531', 'E05013532',
       'E05013533', 'E05013534', 'E05013535', 'E05013536', 'E05013537',
       'E05013538', 'E05013539', 'E05013540', 'E05013541', 'E05013672',
       'E05013673', 'E05013674', 'E05013675', 'E05013676', 'E05013677',
       'E05013678', 'E05013679', 'E05013680', 'E05013681', 'E05013682',
       'E05013683', 'E05013684', 'E05013685', 'E05013686', 'E05013687',
       'E05013688', 'E05013689', 'E05013690', 'E05013691', 'E05013692',
       'E05013693', 'E05013694', 'E05013695', 'E05013696', 'E05014072',
       'E05014073', 'E05014074', 'E05014075', 'E05014076', 'E05014077',
       'E05014078', 'E05014079', 'E05014080', 'E05014081', 'E05014082',
       'E05014083', 'E05014084', 'E05014085', 'E05014086', 'E05014087',
       'E05014088', 'E05014089', 'E05014090', 'E05014091', 'E05014092',
       'E05014093', 'E05014094', 'E05009367', 'E05009368', 'E05009369',
       'E05009370', 'E05009371', 'E05009372', 'E05009373', 'E05009374',
       'E05009375', 'E05009376', 'E05009377', 'E05009378', 'E05009379',
       'E05009381', 'E05009382', 'E05009383', 'E05009384', 'E05009385',
       'E05009386', 'E05009387', 'E05009380', 'E05013733', 'E05013734',
       'E05013735', 'E05013736', 'E05013737', 'E05013738', 'E05013739',
       'E05013740', 'E05013741', 'E05013742', 'E05013743', 'E05013744',
       'E05013745', 'E05013746', 'E05013747', 'E05013748', 'E05013749',
       'E05013750', 'E05013751', 'E05013752', 'E05013753', 'E05013585',
       'E05013586', 'E05013587', 'E05013588', 'E05013589', 'E05013590',
       'E05013591', 'E05013592', 'E05013593', 'E05013594', 'E05013595',
       'E05013596', 'E05013598', 'E05013599', 'E05013597', 'E05013600',
       'E05013601', 'E05013602', 'E05013603', 'E05013604', 'E05013605',
       'E05013542', 'E05013543', 'E05013544', 'E05013545', 'E05013546',
       'E05013547', 'E05013548', 'E05013549', 'E05013550', 'E05013552',
       'E05013553', 'E05013554', 'E05013555', 'E05013556', 'E05013557',
       'E05013559', 'E05013560', 'E05013561', 'E05013562', 'E05013563',
       'E05013967', 'E05013551', 'E05013968', 'E05013969', 'E05013970',
       'E05013971', 'E05013558', 'E05013972', 'E05013973', 'E05013974',
       'E05013975', 'E05013976', 'E05013977', 'E05013978', 'E05013979',
       'E05013980', 'E05013984', 'E05013985', 'E05013981', 'E05013982',
       'E05013986', 'E05013564', 'E05013565', 'E05013983', 'E05013566',
       'E05013567', 'E05013568', 'E05013569', 'E05013570', 'E05013571',
       'E05013573', 'E05013574', 'E05013575', 'E05013576', 'E05013577',
       'E05013578', 'E05013579', 'E05013580', 'E05013581', 'E05013572',
       'E05013582', 'E05013583', 'E05013584', 'E05013606', 'E05013607',
       'E05013608', 'E05013609', 'E05013610', 'E05013611', 'E05013612',
       'E05013613', 'E05013614', 'E05013615', 'E05013616', 'E05013617',
       'E05013618', 'E05013619', 'E05013620', 'E05013621', 'E05013622',
       'E05013623', 'E05013624', 'E05013625', 'E05013626', 'E05013627',
       'E05013697', 'E05013698', 'E05013699', 'E05013700', 'E05013701',
       'E05013702', 'E05013703', 'E05013704', 'E05013705', 'E05013706',
       'E05013707', 'E05013708', 'E05013709', 'E05013710', 'E05013711',
       'E05013712', 'E05013713', 'E05009388', 'E05009389', 'E05009390',
       'E05009391', 'E05009392', 'E05009393', 'E05009394', 'E05009395',
       'E05009396', 'E05009397', 'E05009398', 'E05009399', 'E05009400',
       'E05009401', 'E05009402', 'E05009403', 'E05009404', 'E05009405',
       'E05013928', 'E05013929', 'E05013930', 'E05013931', 'E05013932',
       'E05013933', 'E05013934', 'E05013935', 'E05013936', 'E05013937',
       'E05013938', 'E05013939', 'E05013940', 'E05013941', 'E05013942',
       'E05013943', 'E05013944', 'E05013945', 'E05013946', 'E05014095',
       'E05014096', 'E05014097', 'E05014098', 'E05014099', 'E05014100',
       'E05014101', 'E05014102', 'E05014103', 'E05014104', 'E05014105',
       'E05014106', 'E05014107', 'E05014108', 'E05014109', 'E05014110',
       'E05014111', 'E05014112', 'E05014113', 'E05014114', 'E05014115',
       'E05014116', 'E05014117', 'E05014118', 'E05014119', 'E05013714',
       'E05013715', 'E05013716', 'E05013717', 'E05013718', 'E05013719',
       'E05013720', 'E05013721', 'E05013722', 'E05013723', 'E05013724',
       'E05013725', 'E05013726', 'E05013727', 'E05013728', 'E05013729',
       'E05013730', 'E05013731', 'E05013732', 'E05013810', 'E05013811',
       'E05013812', 'E05013813', 'E05013814', 'E05013815', 'E05013816',
       'E05013817', 'E05013818', 'E05013819', 'E05013820', 'E05013821',
       'E05013822', 'E05013823', 'E05013824', 'E05013825', 'E05013826',
       'E05013827', 'E05013828', 'E05013829', 'E05013904', 'E05013905',
       'E05013906', 'E05013907', 'E05013908', 'E05013909', 'E05013910',
       'E05013911', 'E05013912', 'E05013913', 'E05013914', 'E05013915',
       'E05013916', 'E05013917', 'E05013918', 'E05013919', 'E05013920',
       'E05013921', 'E05013922', 'E05013923', 'E05013924', 'E05013926',
       'E05013927', 'N/K', 'E05013925', 'E05011234', 'E05011235',
       'E05011236', 'E05011237', 'E05011238', 'E05011239', 'E05011240',
       'E05011241', 'E05011242', 'E05011243', 'E05011244', 'E05011245',
       'E05011246', 'E05011247', 'E05011248', 'E05011249', 'E05011250',
       'E05011251', 'E05011252', 'E05011253', 'E05011254', 'E05011255',
       'E05013774', 'E05013775', 'E05013776', 'E05013777', 'E05013778',
       'E05013779', 'E05013780', 'E05013781', 'E05013782', 'E05013783',
       'E05013784', 'E05013786', 'E05013787', 'E05013785', 'E05013788',
       'E05013789', 'E05013790', 'E05013791', 'E05011095', 'E05011096',
       'E05011097', 'E05011098', 'E05011099', 'E05011100', 'E05011101',
       'E05011102', 'E05011103', 'E05011104', 'E05011106', 'E05011107',
       'E05011108', 'E05011109', 'E05011110', 'E05011105', 'E05011111',
       'E05011112', 'E05011113', 'E05011116', 'E05011114', 'E05011115',
       'E05011117', 'E05013754', 'E05013755', 'E05013756', 'E05013757',
       'E05013758', 'E05013759', 'E05013760', 'E05013763', 'E05013761',
       'E05013762', 'E05013764', 'E05013765', 'E05013766', 'E05013767',
       'E05013768', 'E05013769', 'E05013770', 'E05013771', 'E05013773',
       'E05009317', 'E05009331', 'E05009318', 'E05009319', 'E05009320',
       'E05009321', 'E05009322', 'E05009323', 'E05009324', 'E05009325',
       'E05009326', 'E05009327', 'E05009328', 'E05009332', 'E05013772',
       'E05009333', 'E05009329', 'E05009330', 'E05009334', 'E05009335',
       'E05009336', 'E05013882', 'E05013883', 'E05013884', 'E05013885',
       'E05013886', 'E05013887', 'E05013888', 'E05013890', 'E05013891',
       'E05013892', 'E05013893', 'E05013894', 'E05013895', 'E05013896',
       'E05013897', 'E05013898', 'E05013899', 'E05013900', 'E05013901',
       'E05013902', 'E05013903', 'E05014009', 'E05014010', 'E05014011',
       'E05014012', 'E05014013', 'E05014014', 'E05014015', 'E05014016',
       'E05013889', 'E05014017', 'E05014019', 'E05014020', 'E05014021',
       'E05014018', 'E05014023', 'E05014024', 'E05014025', 'E05014026',
       'E05014027', 'E05014028', 'E05014029', 'E05014030', 'E05013792',
       'E05013793', 'E05013794', 'E05013795', 'E05013796', 'E05013797',
       'E05013798', 'E05013799', 'E05013800', 'E05013801', 'E05013802',
       'E05013803', 'E05013804', 'E05013805', 'E05013806', 'E05014022',
       'E05013807', 'E05013808', 'E05013809', 'E05000046', '-1',
       'NON ATHENA FORCE', 'E05000326', 'E05000331', 'E05000649',
       'E05000335', 'E05000428', 'E05000448', 'E05000173', 'E05000139',
       'E05000596', 'E05000085', 'E05000358', 'E05000419', 'E05000143',
       'E05000646', 'E05000170'], dtype=object)

In [199]:
# Area code contain null, "N/K", "-1" and "NON ATHENA FORCE"

In [269]:
df['Area code'].value_counts().loc[['N/K', '-1', 'NON ATHENA FORCE',]]

Area code
N/K                 1674
-1                  1230
NON ATHENA FORCE     434
Name: count, dtype: int64

In [271]:
df['Area code'].isnull().sum()

3219

In [283]:
# Check data type of columns
df.dtypes

Month_Year          datetime64[ns]
Area Type                   object
Borough_SNT                 object
Area name                   object
Area code                   object
Offence Group               object
Offence Subgroup            object
Measure                     object
Financial Year              object
FY_FYIndex                  object
Count                        int64
Refresh Date        datetime64[ns]
dtype: object

In [273]:
# Will leave it like this, if we need it further in solving problem then we'll see

In [279]:
df.to_csv(r'C:\Users\Tesla Laptops\Desktop\Job planning\Portfolio Project\TNO - Crimes in London\data\raw\M1045_MonthlyCrimeDashboard_TNOCrimeData_cleaned.csv', index=False)